name: Update MCU Data
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que pega todo o repositório
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install axios
      - name: Update MCU Data
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
        run: |
          ls -la  # Lista arquivos na raiz
          ls -la scripts/  # Lista arquivos em scripts/
          node scripts/updateMcuData.js  # Executa o script
          cat src/mcuData.js  # Mostra o resultado
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add src/mcuData.js
          git commit -m "Update mcuData.js with new releases" || echo "No changes"
          git push
